// Package store is Janus's crypto-blind PostgreSQL persistence layer. It
// persists and returns opaque encrypted bytes only; it never holds a key or
// plaintext. Repositories map pgx driver errors to the sentinels in errors.go.
package store

import (
	"context"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Store owns the connection pool and the DSN (the DSN is reused by Migrate).
type Store struct {
	pool *pgxpool.Pool
	dsn  string
}

// PoolConfig tunes the pgx connection pool. Every field is optional: a zero
// value means "leave pgx's own default in place" (which is what Open uses).
// cmd/janus populates this from the JANUS_DB_* environment; tests construct it
// directly.
type PoolConfig struct {
	// MaxConns caps the pool size. <= 0 keeps pgx's default (max(4, NumCPU)).
	MaxConns int32
	// MinConns is the number of idle connections the pool keeps warm. <= 0
	// keeps pgx's default (0).
	MinConns int32
	// MaxConnLifetime bounds how long a connection may live before it is
	// retired. <= 0 keeps pgx's default (1h).
	MaxConnLifetime time.Duration
	// MaxConnIdleTime bounds how long an idle connection may sit before it is
	// closed. <= 0 keeps pgx's default (30m).
	MaxConnIdleTime time.Duration
}

// apply overlays the non-zero PoolConfig fields onto a parsed pgxpool.Config.
func (pc PoolConfig) apply(cfg *pgxpool.Config) {
	if pc.MaxConns > 0 {
		cfg.MaxConns = pc.MaxConns
	}
	if pc.MinConns > 0 {
		cfg.MinConns = pc.MinConns
	}
	if pc.MaxConnLifetime > 0 {
		cfg.MaxConnLifetime = pc.MaxConnLifetime
	}
	if pc.MaxConnIdleTime > 0 {
		cfg.MaxConnIdleTime = pc.MaxConnIdleTime
	}
}

// Open connects to Postgres with pgx's default pool settings and verifies the
// connection. dsn is a postgres://... URL. It is shorthand for
// OpenWithConfig(ctx, dsn, PoolConfig{}).
func Open(ctx context.Context, dsn string) (*Store, error) {
	return OpenWithConfig(ctx, dsn, PoolConfig{})
}

// OpenWithConfig connects to Postgres applying any non-zero PoolConfig tuning
// on top of the DSN-derived defaults, then verifies the connection.
func OpenWithConfig(ctx context.Context, dsn string, pc PoolConfig) (*Store, error) {
	cfg, err := pgxpool.ParseConfig(dsn)
	if err != nil {
		return nil, fmt.Errorf("store: parse dsn: %w", err)
	}
	pc.apply(cfg)
	pool, err := pgxpool.NewWithConfig(ctx, cfg)
	if err != nil {
		return nil, fmt.Errorf("store: open pool: %w", err)
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("store: ping: %w", err)
	}
	return &Store{pool: pool, dsn: dsn}, nil
}

// Close releases the pool.
func (s *Store) Close() { s.pool.Close() }

// Ping verifies connectivity.
func (s *Store) Ping(ctx context.Context) error { return s.pool.Ping(ctx) }

// withTx runs fn inside a transaction, committing on nil and rolling back
// otherwise. The rollback after a successful commit is a no-op.
func (s *Store) withTx(ctx context.Context, fn func(pgx.Tx) error) error {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return err
	}
	defer func() { _ = tx.Rollback(ctx) }()
	if err := fn(tx); err != nil {
		return err
	}
	return tx.Commit(ctx)
}

// execAffectingOne runs a write that is expected to touch exactly one row. It
// maps driver errors to store sentinels and returns ErrNotFound when no row
// matched — the shared shape behind every repo's SoftDelete/Undelete/Destroy.
func (s *Store) execAffectingOne(ctx context.Context, sql string, args ...any) error {
	tag, err := s.pool.Exec(ctx, sql, args...)
	if err != nil {
		return mapError(err)
	}
	if tag.RowsAffected() == 0 {
		return ErrNotFound
	}
	return nil
}

// NewID returns a fresh UUID as text, generated by Postgres. It lets a caller
// learn a row's id before insert (e.g. to bind key-wrapping AAD to it).
func (s *Store) NewID(ctx context.Context) (string, error) {
	var id string
	if err := s.pool.QueryRow(ctx, `SELECT gen_random_uuid()::text`).Scan(&id); err != nil {
		return "", mapError(err)
	}
	return id, nil
}
